<?php

namespace Database\Seeders;

use App\Models\CodeGlosa;
use Illuminate\Database\Seeder;

class CodeGlosaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CodeGlosa::insert([
            ['id' => '101', 'general_code_glosa_id' => 1, 'code' => '101', 'description' => 'Estancia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '102', 'general_code_glosa_id' => 1, 'code' => '102', 'description' => 'Consultas, interconsultas y visitas médicas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '103', 'general_code_glosa_id' => 1, 'code' => '103', 'description' => 'Honorarios médicos en procedimientos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '104', 'general_code_glosa_id' => 1, 'code' => '104', 'description' => 'Honorarios otros profesionales asistenciales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '105', 'general_code_glosa_id' => 1, 'code' => '105', 'description' => 'Derechos de sala', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '106', 'general_code_glosa_id' => 1, 'code' => '106', 'description' => 'Materiales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '107', 'general_code_glosa_id' => 1, 'code' => '107', 'description' => 'Medicamentos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '108', 'general_code_glosa_id' => 1, 'code' => '108', 'description' => 'Ayudas diagnósticas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '109', 'general_code_glosa_id' => 1, 'code' => '109', 'description' => 'Atención integral (caso, conjunto integral de atenciones, paquete o grupo relacionado por diagnóstico)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '110', 'general_code_glosa_id' => 1, 'code' => '110', 'description' => 'Servicio o insumo incluido en caso, conjunto integral de atenciones, paquete o grupo relacionado por diagnóstico', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '111', 'general_code_glosa_id' => 1, 'code' => '111', 'description' => 'Servicio o insumo incluido en estancia o derechos de sala', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '112', 'general_code_glosa_id' => 1, 'code' => '112', 'description' => 'Factura excede topes autorizados', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '113', 'general_code_glosa_id' => 1, 'code' => '113', 'description' => 'Facturar por separado por tipo de recobro (Comité Técnico Científico, (CTC), accidente de trabajo o enfermedad profesional (ATEP), tutelas)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '114', 'general_code_glosa_id' => 1, 'code' => '114', 'description' => 'Error en suma de conceptos facturados', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '115', 'general_code_glosa_id' => 1, 'code' => '115', 'description' => 'Datos insuficientes del usuario', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '116', 'general_code_glosa_id' => 1, 'code' => '116', 'description' => 'Usuario o servicio corresponde a otro plan o responsable', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '117', 'general_code_glosa_id' => 1, 'code' => '117', 'description' => 'Usuario retirado o moroso', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '119', 'general_code_glosa_id' => 1, 'code' => '119', 'description' => 'Error en descuento pactado', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '120', 'general_code_glosa_id' => 1, 'code' => '120', 'description' => 'Recibo de pago compartido', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '122', 'general_code_glosa_id' => 1, 'code' => '122', 'description' => 'Prescripción dentro de los términos legales o pactados entre las partes', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '123', 'general_code_glosa_id' => 1, 'code' => '123', 'description' => 'Procedimiento o actividad', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '124', 'general_code_glosa_id' => 1, 'code' => '124', 'description' => 'Falta firma del prestador de servicios de salud', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '125', 'general_code_glosa_id' => 1, 'code' => '125', 'description' => 'Examen o actividad pertenece a detección temprana y protección especifica', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '126', 'general_code_glosa_id' => 1, 'code' => '126', 'description' => 'Usuario o servicio corresponde a capitación', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '127', 'general_code_glosa_id' => 1, 'code' => '127', 'description' => 'Servicio o procedimiento incluido en otro', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '128', 'general_code_glosa_id' => 1, 'code' => '128', 'description' => 'Orden cancelada al prestador de servicios de salud', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '151', 'general_code_glosa_id' => 1, 'code' => '151', 'description' => 'Recobro en contrato de capitación por servicios prestados por otro prestador', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '152', 'general_code_glosa_id' => 1, 'code' => '152', 'description' => 'Disminución en el número de personas incluidas en la capitación', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '154', 'general_code_glosa_id' => 1, 'code' => '154', 'description' => 'Incumplimiento en las metas de cobertura, resolutividad y oportunidades pactadas en el contrato por capitación', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '201', 'general_code_glosa_id' => 2, 'code' => '201', 'description' => 'Estancia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '202', 'general_code_glosa_id' => 2, 'code' => '202', 'description' => 'Consultas, interconsultas y visitas médicas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '203', 'general_code_glosa_id' => 2, 'code' => '203', 'description' => 'Honorarios médicos en procedimientos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '204', 'general_code_glosa_id' => 2, 'code' => '204', 'description' => 'Honorarios otros profesionales asistenciales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '205', 'general_code_glosa_id' => 2, 'code' => '205', 'description' => 'Derechos de sala', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '206', 'general_code_glosa_id' => 2, 'code' => '206', 'description' => 'Materiales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '207', 'general_code_glosa_id' => 2, 'code' => '207', 'description' => 'Medicamentos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '208', 'general_code_glosa_id' => 2, 'code' => '208', 'description' => 'Ayudas diagnósticas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '209', 'general_code_glosa_id' => 2, 'code' => '209', 'description' => 'Atención integral (caso, conjunto integral de atenciones, paquete o grupo relacionado por diagnóstico)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '223', 'general_code_glosa_id' => 2, 'code' => '223', 'description' => 'Procedimiento o actividad', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '229', 'general_code_glosa_id' => 2, 'code' => '229', 'description' => 'Recargos no pactados', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '301', 'general_code_glosa_id' => 3, 'code' => '301', 'description' => 'Estancia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '302', 'general_code_glosa_id' => 3, 'code' => '302', 'description' => 'Consultas, interconsultas y visitas médicas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '303', 'general_code_glosa_id' => 3, 'code' => '303', 'description' => 'Honorarios médicos en procedimientos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '304', 'general_code_glosa_id' => 3, 'code' => '304', 'description' => 'Honorarios otros profesionales asistenciales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '307', 'general_code_glosa_id' => 3, 'code' => '307', 'description' => 'Medicamentos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '308', 'general_code_glosa_id' => 3, 'code' => '308', 'description' => 'Ayudas diagnósticas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '309', 'general_code_glosa_id' => 3, 'code' => '309', 'description' => 'Atención integral (caso, conjunto integral de atenciones, paquete o grupo relacionado por diagnóstico)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '320', 'general_code_glosa_id' => 3, 'code' => '320', 'description' => 'Recibo de pago compartido', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '330', 'general_code_glosa_id' => 3, 'code' => '330', 'description' => 'Autorización de servicios adicional', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '331', 'general_code_glosa_id' => 3, 'code' => '331', 'description' => 'Bonos o vouchers sin firma del paciente, con enmendaduras o tachones', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '332', 'general_code_glosa_id' => 3, 'code' => '332', 'description' => 'Detalle de cargos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '333', 'general_code_glosa_id' => 3, 'code' => '333', 'description' => 'Copia de historia clínica completa', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '335', 'general_code_glosa_id' => 3, 'code' => '335', 'description' => 'Formato accidente de trabajo y enfermedad profesional ATEP', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '336', 'general_code_glosa_id' => 3, 'code' => '336', 'description' => 'Copia de factura o detalle de cargos del seguro obligatorio de accidentes de tránsito SOAT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '337', 'general_code_glosa_id' => 3, 'code' => '337', 'description' => 'Orden o fórmula médica', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '338', 'general_code_glosa_id' => 3, 'code' => '338', 'description' => 'Hoja de traslado en ambulancia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '339', 'general_code_glosa_id' => 3, 'code' => '339', 'description' => 'Comprobante de recibido del usuario', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '340', 'general_code_glosa_id' => 3, 'code' => '340', 'description' => 'Registro de anestesia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '341', 'general_code_glosa_id' => 3, 'code' => '341', 'description' => 'Descripción quirúrgica', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '342', 'general_code_glosa_id' => 3, 'code' => '342', 'description' => 'Lista de precios', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '343', 'general_code_glosa_id' => 3, 'code' => '343', 'description' => 'Orden o autorización de servicios vencida', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '401', 'general_code_glosa_id' => 4, 'code' => '401', 'description' => 'Estancia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '402', 'general_code_glosa_id' => 4, 'code' => '402', 'description' => 'Consultas, interconsultas y visitas médicas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '406', 'general_code_glosa_id' => 4, 'code' => '406', 'description' => 'Materiales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '408', 'general_code_glosa_id' => 4, 'code' => '408', 'description' => 'Ayudas diagnósticas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '423', 'general_code_glosa_id' => 4, 'code' => '423', 'description' => 'Procedimiento o actividad', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '430', 'general_code_glosa_id' => 4, 'code' => '430', 'description' => 'Autorización de servicios adicionales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '438', 'general_code_glosa_id' => 4, 'code' => '438', 'description' => 'Traslado en ambulancia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '443', 'general_code_glosa_id' => 4, 'code' => '443', 'description' => 'Orden o autorización de servicios vencida', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '444', 'general_code_glosa_id' => 4, 'code' => '444', 'description' => 'Médico que ordena no adscrito', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '501', 'general_code_glosa_id' => 5, 'code' => '501', 'description' => 'Estancia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '502', 'general_code_glosa_id' => 5, 'code' => '502', 'description' => 'Consultas, interconsultas y visitas médicas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '506', 'general_code_glosa_id' => 5, 'code' => '506', 'description' => 'Materiales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '507', 'general_code_glosa_id' => 5, 'code' => '507', 'description' => 'Medicamentos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '508', 'general_code_glosa_id' => 5, 'code' => '508', 'description' => 'Ayudas diagnósticas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '523', 'general_code_glosa_id' => 5, 'code' => '523', 'description' => 'Procedimiento o actividad', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '527', 'general_code_glosa_id' => 5, 'code' => '527', 'description' => 'Servicio o procedimiento incluido en otro', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '545', 'general_code_glosa_id' => 5, 'code' => '545', 'description' => 'Servicio no pactado', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '546', 'general_code_glosa_id' => 5, 'code' => '546', 'description' => 'Cobertura sin agotar en la póliza Seguro obligatorio de accidentes de tránsito (SOAT)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '601', 'general_code_glosa_id' => 6, 'code' => '601', 'description' => 'Estancia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '602', 'general_code_glosa_id' => 6, 'code' => '602', 'description' => 'Consultas, interconsultas y visitas médicas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '603', 'general_code_glosa_id' => 6, 'code' => '603', 'description' => 'Honorarios médicos en procedimientos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '604', 'general_code_glosa_id' => 6, 'code' => '604', 'description' => 'Honorarios otros profesionales asistenciales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '605', 'general_code_glosa_id' => 6, 'code' => '605', 'description' => 'Derechos de sala', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '606', 'general_code_glosa_id' => 6, 'code' => '606', 'description' => 'Materiales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '607', 'general_code_glosa_id' => 6, 'code' => '607', 'description' => 'Medicamentos', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '608', 'general_code_glosa_id' => 6, 'code' => '608', 'description' => 'Ayudas diagnósticas', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '623', 'general_code_glosa_id' => 6, 'code' => '623', 'description' => 'Procedimiento o actividad', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '653', 'general_code_glosa_id' => 6, 'code' => '653', 'description' => 'Urgencia no pertinente', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '816', 'general_code_glosa_id' => 8, 'code' => '816', 'description' => 'Usuario o servicio corresponde a otro plan o responsable', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '817', 'general_code_glosa_id' => 8, 'code' => '817', 'description' => 'Usuario retirado o moroso', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '821', 'general_code_glosa_id' => 8, 'code' => '821', 'description' => 'Autorización principal no existe no corresponde al prestador de servicios de salud', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '834', 'general_code_glosa_id' => 8, 'code' => '834', 'description' => 'Resumen de egreso o epicrisis, hoja de atención de urgencias u odontograma', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '844', 'general_code_glosa_id' => 8, 'code' => '844', 'description' => 'Médico que ordena no adscrito', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '847', 'general_code_glosa_id' => 8, 'code' => '847', 'description' => 'Faltan soportes de justificación para recobros (Comité Técnico Científico, (CTC), accidente de trabajo o enfermedad profesional (ATEP), tutelas)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '848', 'general_code_glosa_id' => 8, 'code' => '848', 'description' => 'Informe de atención inicial de urgencias', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '849', 'general_code_glosa_id' => 8, 'code' => '849', 'description' => 'Factura no cumple requisitos legales', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '850', 'general_code_glosa_id' => 8, 'code' => '850', 'description' => 'Factura ya cancelada', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '996', 'general_code_glosa_id' => 9, 'code' => '996', 'description' => 'Glosa o devolución injustificada', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '997', 'general_code_glosa_id' => 9, 'code' => '997', 'description' => 'No subsanada (Glosa o devolución totalmente aceptada)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '998', 'general_code_glosa_id' => 9, 'code' => '998', 'description' => 'Subsanada parcial (Glosa o devolución parcialmente aceptada)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '999', 'general_code_glosa_id' => 9, 'code' => '999', 'description' => 'Subsanada (Glosa o Devolución No Aceptada)', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
